# Generated by Django 4.1.3 on 2023-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HTML', models.CharField(max_length=50)),
                ('CSS', models.CharField(max_length=50)),
                ('JAVASCRIPT', models.CharField(max_length=50)),
                ('PYTHON', models.CharField(max_length=50)),
                ('DJANGO', models.CharField(max_length=50)),
            ],
        ),
    ]
